- name: Clair Scanner Server Setup
  hosts: build
  become: true
  vars:
    image_to_scan: "{{ var_docker_hub_login }}/mysql-image"  #container to scan for vulnerabilities
    image_tag: repository_tag
    clair_server: "172.17.0.1"  #clair server api endpoint
  pre_tasks:
    - name: setting up clair-db
      docker_container:
        name: clair_db
        image: arminc/clair-db:2017-09-18
        exposed_ports:
          - 5432

    - name: setting up clair-local-scan
      docker_container:
        name: clair
        image: arminc/clair-local-scan:v2.0.6
        ports:
          - "6060:6060"
        links:
          - "clair_db:postgres"

    - debug:
        msg: "It will take some time to update the CVE databasae"
  tasks:
    - name: downloading and setting up clair-scanner binary
      get_url:
        url: https://github.com/arminc/clair-scanner/releases/download/v6/clair-scanner_linux_amd64
        dest: /usr/local/bin/clair-scanner
        mode: 0755
    
    - name: scanning {{ image_to_scan }} container for vulnerabilities
      shell: "/usr/local/bin/clair-scanner -r /tmp/{{ image_to_scan | basename }}-scan-report.json -c http://{{ clair_server }}:6060 --ip {{ clair_server }} {{ image_to_scan }}:{{ image_tag }}"
      register: scan_output
      ignore_errors: yes

#    - name: exit if some CVE is found
#      fail:
#        msg: "the command failed"
#      when: "'CVE-2018-' in scan_output.stderr"
